/** Event-bound Homebrew publication. Network writes are confined to publish(). */
import {createHash} from 'node:crypto';
import {mkdir, readFile, writeFile} from 'node:fs/promises';
import {resolve} from 'node:path';
import {pathToFileURL} from 'node:url';

export const SOURCE = 'SijanC147/pure';
export const TAP = 'SijanC147/homebrew-formulas';
const FORMULA = 'Formula/pure.rb';
const shaPattern = /^[a-f0-9]{40}$/;
const digestPattern = /^[a-f0-9]{64}$/;
export interface ReleaseProof {tag: string; version: string; baseVersion: string; sourceVersion: string; commit: string; releaseId: number; archiveSha256: string; formulaSha256: string}
interface Release {id: number; tag_name: string; draft: boolean; prerelease: boolean; published_at: string | null}
interface Ref {object: {type: string; sha: string}}
interface Commit {sha: string; tree: {sha: string}; parents: {sha: string}[]}
interface Pull {number: number; state: string; merged_at: string | null; head: {sha: string; ref: string; repo: {full_name: string}}; base: {sha: string; ref: string; repo: {full_name: string}}}
export type Api = <T>(path: string, method?: string, body?: unknown) => Promise<T>;

/** Parse an immutable fork tag, rejecting Ruby/URL injection and impossible dates. */
export function parseTag(tag: string): {version: string; baseVersion: string} {
  const match = /^v((?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*))(?:\+(\d{14}))?$/.exec(tag);
  if (!match) throw new Error('Expected vX.Y.Z or vX.Y.Z+yyyyMMddHHmmss release tag');
  const stamp = match[2];
  if (!stamp) return {version: tag.slice(1), baseVersion: match[1]!};
  const iso = `${stamp.slice(0, 4)}-${stamp.slice(4, 6)}-${stamp.slice(6, 8)}T${stamp.slice(8, 10)}:${stamp.slice(10, 12)}:${stamp.slice(12, 14)}Z`;
  const date = new Date(iso);
  if (!Number.isFinite(date.valueOf()) || date.toISOString().slice(0, 19) !== iso.slice(0, 19)) throw new Error('Invalid release timestamp');
  return {version: tag.slice(1), baseVersion: match[1]!};
}
/** Compare numeric base versions first, then monotonically ordered build timestamps. */
export function compareVersions(a: string, b: string): number {
  const parts = (v: string) => {
    if (!/^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)(?:\+\d{14})?$/.test(v)) throw new Error(`Unsupported tap version: ${v}`);
    return v.split(/[.+]/).map(BigInt);
  };
  const left = parts(a); const right = parts(b);
  for (let i = 0; i < 4; i++) {
    if ((left[i] ?? 0n) > (right[i] ?? 0n)) return 1;
    if ((left[i] ?? 0n) < (right[i] ?? 0n)) return -1;
  }
  return 0;
}
/** Canonical public tag archive URL. */
export function archiveUrl(tag: string): string {parseTag(tag); return `https://github.com/${SOURCE}/archive/refs/tags/${tag}.tar.gz`;}
/** Render an exact formula with an explicit version; archive autodetection loses the base. */
export function renderFormula(tag: string, checksum: string): string {
  const {version} = parseTag(tag);
  if (!digestPattern.test(checksum)) throw new Error('Invalid archive checksum');
  return `# Generated by the verified Pure release workflow.\nclass Pure < Formula\n  desc "Pretty, minimal and fast zsh prompt"\n  homepage "https://github.com/${SOURCE}"\n  url "${archiveUrl(tag)}"\n  version "${version}"\n  sha256 "${checksum}"\n  license "MIT"\n\n  depends_on "zsh" => :test\n  depends_on "zsh-async"\n\n  def install\n    zsh_function.install "pure.zsh" => "prompt_pure_setup"\n  end\n\n  test do\n    command = "setopt prompt_subst; fpath=(#{zsh_function} #{Formula[\"zsh-async\"].opt_share}/zsh/site-functions $fpath); autoload -U promptinit; promptinit; prompt -p pure"\n    assert_match "❯", shell_output("zsh -fc '#{command}'")\n  end\nend\n`;
}
/** Read only the version from the known formula format; ambiguity fails closed. */
export function formulaVersion(formula: string): string {
  const explicit = [...formula.matchAll(/^  version "([^"]+)"$/gm)];
  if (explicit.length === 1) return explicit[0]![1]!;
  if (explicit.length > 1) throw new Error('Ambiguous formula version');
  const legacy = /^  url "https:\/\/github\.com\/SijanC147\/pure\/archive\/refs\/tags\/v([0-9.+]+)\.tar\.gz"$/m.exec(formula);
  if (!legacy) throw new Error('Cannot identify current tap version');
  return legacy[1]!;
}
const digest = (data: string | Uint8Array) => createHash('sha256').update(data).digest('hex');
const requireSha = (sha: string) => {if (!shaPattern.test(sha)) throw new Error('Invalid commit SHA'); return sha;};
const api: Api = async <T,>(path: string, method = 'GET', body?: unknown): Promise<T> => {
  if (!path.startsWith(`repos/${SOURCE}/`) && !path.startsWith(`repos/${TAP}/`)) throw new Error('Repository outside allowlist');
  if (method !== 'GET' && !path.startsWith(`repos/${TAP}/`)) throw new Error('Source repository is read-only');
  const response = await fetch(`https://api.github.com/${path}`, {method, signal: AbortSignal.timeout(60_000), headers: {Accept: 'application/vnd.github+json', Authorization: `Bearer ${process.env.GH_TOKEN ?? ''}`, 'X-GitHub-Api-Version': '2022-11-28'}, ...(body === undefined ? {} : {body: JSON.stringify(body)})});
  if (!response.ok) throw new Error(`GitHub ${method} ${path}: ${response.status}`);
  return await response.json() as T;
};
/** Verify published release, exact tag commit and reachability from current source main. */
export async function releaseBinding(tag: string, request: Api = api): Promise<{releaseId: number; commit: string; baseVersion: string; sourceVersion: string; version: string}> {
  const parsed = parseTag(tag);
  const release = await request<Release>(`repos/${SOURCE}/releases/tags/${encodeURIComponent(tag)}`);
  if (release.tag_name !== tag || release.draft || release.prerelease || !release.published_at || !Number.isSafeInteger(release.id)) throw new Error('Release must be published and stable');
  let object = (await request<Ref>(`repos/${SOURCE}/git/ref/tags/${encodeURIComponent(tag)}`)).object;
  for (let i = 0; object.type === 'tag' && i < 5; i++) object = (await request<Ref>(`repos/${SOURCE}/git/tags/${requireSha(object.sha)}`)).object;
  if (object.type !== 'commit') throw new Error('Tag does not resolve to a commit');
  const commit = requireSha(object.sha);
  const main = requireSha((await request<Ref>(`repos/${SOURCE}/git/ref/heads/main`)).object.sha);
  const comparison = await request<{status: string}>(`repos/${SOURCE}/compare/${commit}...${main}`);
  if (!['ahead', 'identical'].includes(comparison.status)) throw new Error('Release commit is not an ancestor of source main');
  const content = async (path: string) => Buffer.from((await request<{content: string}>(`repos/${SOURCE}/contents/${path}?ref=${commit}`)).content, 'base64').toString('utf8');
  const pkg = JSON.parse(await content('package.json')) as {version: string};
  const runtime = /^\s*prompt_pure_state\[version\]="([^"]+)"/m.exec(await content('pure.zsh'))?.[1];
  if (!/^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)$/.test(pkg.version) || pkg.version !== runtime || (!tag.includes('+') && pkg.version !== parsed.baseVersion)) throw new Error('Source package/runtime versions disagree');
  return {...parsed, sourceVersion: pkg.version, releaseId: release.id, commit};
}
async function downloadArchive(tag: string): Promise<Uint8Array> {
  const response = await fetch(archiveUrl(tag), {signal: AbortSignal.timeout(60_000)});
  if (!response.ok) throw new Error(`Archive download failed: ${response.status}`);
  const bytes = new Uint8Array(await response.arrayBuffer());
  if (bytes.length < 100 || bytes.length > 20_000_000) throw new Error('Unexpected archive size');
  return bytes;
}
/** Recreate and check every artifact byte before the credential-bearing publisher runs. */
export function validateProof(proof: ReleaseProof, archive: Uint8Array, formula: string): void {
  const parsed = parseTag(proof.tag);
  requireSha(proof.commit);
  if (proof.version !== parsed.version || proof.baseVersion !== parsed.baseVersion || !/^(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)\.(?:0|[1-9]\d*)$/.test(proof.sourceVersion) || !Number.isSafeInteger(proof.releaseId)) throw new Error('Invalid release proof');
  if (!digestPattern.test(proof.archiveSha256) || digest(archive) !== proof.archiveSha256) throw new Error('Archive integrity mismatch');
  if (formula !== renderFormula(proof.tag, proof.archiveSha256) || digest(formula) !== proof.formulaSha256) throw new Error('Formula integrity mismatch');
}
/** Refuse pending/failed checks; zero checks are allowed only on a tap without active workflows. */
export async function requireTapChecks(head: string, request: Api): Promise<void> {
  requireSha(head);
  const prefix = `repos/${TAP}`;
  const checks = await request<{total_count: number; check_runs: {status: string; conclusion: string | null}[]}>(`${prefix}/commits/${head}/check-runs?filter=latest&per_page=100`);
  const statuses = await request<{total_count: number; statuses: {state: string}[]}>(`${prefix}/commits/${head}/status?per_page=100`);
  const workflows = await request<{total_count: number; workflows: {state: string}[]}>(`${prefix}/actions/workflows?per_page=100`);
  if (checks.total_count > 100 || statuses.total_count > 100 || workflows.total_count > 100) throw new Error('Tap check listing is incomplete');
  if (checks.check_runs.some(check => check.status !== 'completed' || check.conclusion !== 'success') || statuses.statuses.some(status => status.state !== 'success')) throw new Error('Tap checks are pending or failed; retry after they pass');
  if (checks.check_runs.length + statuses.statuses.length === 0 && workflows.workflows.some(workflow => workflow.state === 'active')) throw new Error('Active tap workflows have not reported checks yet');
}
/** Require Actions to execute the same immutable source commit being published. */
export function requireWorkflowBinding(tag: string, commit: string, env: NodeJS.ProcessEnv): void {
  if (env.GITHUB_ACTIONS !== 'true') return;
  if (env.GITHUB_REPOSITORY !== SOURCE || !['release', 'workflow_dispatch'].includes(env.GITHUB_EVENT_NAME ?? '') || env.GITHUB_SHA !== commit || env.GITHUB_REF !== `refs/tags/${tag}`) throw new Error('Workflow must run on the exact published source tag and commit');
}
/** Prepare deterministic artifacts without publication credentials. */
export async function prepare(tag: string, directory: string): Promise<void> {
  const binding = await releaseBinding(tag);
  requireWorkflowBinding(tag, binding.commit, process.env);
  if (process.env.GITHUB_EVENT_NAME === 'release') {
    const event = JSON.parse(await readFile(process.env.GITHUB_EVENT_PATH!, 'utf8')) as {release: Release};
    if (event.release.tag_name !== tag || event.release.id !== binding.releaseId) throw new Error('Release event binding mismatch');
  }
  const archive = await downloadArchive(tag);
  const archiveSha256 = digest(archive);
  const formula = renderFormula(tag, archiveSha256);
  const proof: ReleaseProof = {...binding, tag, archiveSha256, formulaSha256: digest(formula)};
  await mkdir(directory, {recursive: true});
  await writeFile(resolve(directory, 'release.json'), `${JSON.stringify(proof, null, 2)}\n`);
  await writeFile(resolve(directory, 'pure.rb'), formula);
  await writeFile(resolve(directory, 'archive.tar.gz'), archive);
  console.log(`Prepared ${tag} at ${binding.commit}`);
}
/** Publish an exact formula through a normal, narrowly scoped pull request. */
export async function publish(directory: string, request: Api = api, download = downloadArchive, environment: NodeJS.ProcessEnv = process.env): Promise<void> {
  const proof = JSON.parse(await readFile(resolve(directory, 'release.json'), 'utf8')) as ReleaseProof;
  const formula = await readFile(resolve(directory, 'pure.rb'), 'utf8');
  const archive = await readFile(resolve(directory, 'archive.tar.gz'));
  validateProof(proof, archive, formula);
  requireWorkflowBinding(proof.tag, proof.commit, environment);
  const binding = await releaseBinding(proof.tag, request);
  if (binding.commit !== proof.commit || binding.releaseId !== proof.releaseId || binding.sourceVersion !== proof.sourceVersion) throw new Error('Release changed after verification');
  if (digest(await download(proof.tag)) !== proof.archiveSha256) throw new Error('Published archive changed after verification');
  const prefix = `repos/${TAP}`;
  const mainSha = async () => requireSha((await request<Ref>(`${prefix}/git/ref/heads/main`)).object.sha);
  const base = await mainSha();
  const current = Buffer.from((await request<{content: string}>(`${prefix}/contents/${FORMULA}?ref=${base}`)).content, 'base64').toString('utf8');
  if (current === formula) {console.log(`Tap already publishes exact verified ${proof.tag}`); return;}
  if (compareVersions(proof.version, formulaVersion(current)) <= 0) throw new Error('Refusing tap downgrade or different content at same version');
  const branch = `release/pure-${proof.tag}`;
  const refs = await request<{ref: string; object: {sha: string}}[]>(`${prefix}/git/matching-refs/heads/${encodeURIComponent(branch)}`);
  const existing = refs.find(ref => ref.ref === `refs/heads/${branch}`);
  let head: string;
  if (existing) {
    head = requireSha(existing.object.sha);
    const branchFormula = Buffer.from((await request<{content: string}>(`${prefix}/contents/${FORMULA}?ref=${head}`)).content, 'base64').toString('utf8');
    const commit = await request<Commit>(`${prefix}/git/commits/${head}`);
    if (branchFormula !== formula || commit.parents.length !== 1 || commit.parents[0]!.sha !== base) throw new Error('Existing publication branch conflicts with current tap main');
  } else {
    const baseCommit = await request<Commit>(`${prefix}/git/commits/${base}`);
    const tree = await request<{sha: string}>(`${prefix}/git/trees`, 'POST', {base_tree: baseCommit.tree.sha, tree: [{path: FORMULA, mode: '100644', type: 'blob', content: formula}]});
    const commit = await request<{sha: string}>(`${prefix}/git/commits`, 'POST', {message: `chore: publish Pure ${proof.tag}`, tree: tree.sha, parents: [base]});
    head = requireSha(commit.sha);
    if (await mainSha() !== base) throw new Error('Tap main changed during preparation');
    await request(`${prefix}/git/refs`, 'POST', {ref: `refs/heads/${branch}`, sha: head});
  }
  const pulls = await request<Pull[]>(`${prefix}/pulls?state=all&head=${encodeURIComponent(`SijanC147:${branch}`)}&base=main&per_page=100`);
  if (pulls.length > 1) throw new Error('Ambiguous publication pull requests');
  let pull = pulls[0];
  if (!pull) pull = await request<Pull>(`${prefix}/pulls`, 'POST', {title: `Publish Pure ${proof.tag}`, head: branch, base: 'main', body: `Publish [Pure ${proof.tag}](https://github.com/${SOURCE}/releases/tag/${proof.tag}) from source commit ${proof.commit}.\n\nThe exact tagged archive, explicit Homebrew version, checksum, installation and formula test were verified on hosted macOS before this PR was created. Only Formula/pure.rb changes.\n\nArchive SHA-256: ${proof.archiveSha256}`});
  pull = await request<Pull>(`${prefix}/pulls/${pull.number}`);
  if (pull.state !== 'open' || pull.merged_at || pull.head.sha !== head || pull.head.ref !== branch || pull.head.repo.full_name !== TAP || pull.base.sha !== base || pull.base.ref !== 'main' || pull.base.repo.full_name !== TAP) throw new Error('Pull request binding changed');
  const files = await request<{filename: string; status: string}[]>(`${prefix}/pulls/${pull.number}/files?per_page=100`);
  if (files.length !== 1 || files[0]!.filename !== FORMULA || files[0]!.status !== 'modified') throw new Error('Publication PR must change only the existing Pure formula');
  await requireTapChecks(head, request);
  if (await mainSha() !== base) throw new Error('Tap main changed before merge');
  const finalPull = await request<Pull>(`${prefix}/pulls/${pull.number}`);
  if (finalPull.head.sha !== head || finalPull.base.sha !== base || finalPull.state !== 'open') throw new Error('Pull request changed before merge');
  const merged = await request<{merged: boolean; sha: string}>(`${prefix}/pulls/${pull.number}/merge`, 'PUT', {sha: head, merge_method: 'merge'});
  if (!merged.merged) throw new Error('Normal PR merge did not succeed');
  const finalMain = await mainSha();
  if (finalMain !== merged.sha) throw new Error('Tap main advanced during publication; inspect manually');
  const finalFormula = Buffer.from((await request<{content: string}>(`${prefix}/contents/${FORMULA}?ref=${finalMain}`)).content, 'base64').toString('utf8');
  if (finalFormula !== formula) throw new Error('Merged tap formula differs from verified artifact');
  console.log(`Published ${proof.tag}: https://github.com/${TAP}/pull/${pull.number}, tap main ${finalMain}`);
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  const [command, value, directory] = process.argv.slice(2);
  if (command === 'prepare' && value && directory) await prepare(value, directory);
  else if (command === 'publish' && value) await publish(value);
  else throw new Error('Usage: homebrew-release.mts prepare TAG DIRECTORY | publish DIRECTORY');
}
